version: '3'

services:
  # Plataforma de recolección de métricas HTTP de los servicios monitoreados
  prometheus:
    image: prom/prometheus
    volumes:
      # Volumen de configuración
      - ./prometheus/:/etc/prometheus/
      # Volumen de datos
      - prometheus-data:/prometheus
    restart: "always"
    networks:
      - backend
    ports:
      - 9090:9090
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
  # Analiza los recursos usados por los contendores
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    privileged: true
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
    #devices:
      #- /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - backend
    restart: "always"
    labels:
      org.label-schema.group: "monitoring"
  # Visor de métricas y datos
  grafana:
    image: grafana/grafana:9.0.5
    depends_on: 
      - prometheus
    expose: 
      - 3000
    volumes:
      # Volumen de datos
      - grafana_data:/var/lib/grafana
      # Volumen de configuración
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    networks:
      - backend
    restart: "always"
  redis:
    image: redis

    ports:
      - 6379:6379

networks:
  frontend:
  backend:

volumes:
  prometheus-data: {}
  grafana_data: {}

