version: '3'

services:
  # Plataforma de recolección de métricas HTTP de los servicios monitoreados
  prometheus:
    image: prom/prometheus
    volumes:
      # Volumen de configuración
      - ./prometheus/:/etc/prometheus/
      # Volumen de datos
      - prometheus-data:/prometheus
    restart: "always"
    networks:
      - backend
    ports:
      - 9090:9090
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - cadvisor:cadvisor
  # Analiza los recursos usados por los contendores
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
    ports:
      - 8080:8080
    networks:
      - backend
    restart: "always"
  # Visor de métricas y datos
  grafana:
    image: grafana/grafana
    depends_on: 
      - prometheus
    ports: 
      - 3000:3000
    volumes:
      # Volumen de datos
      - grafana_data:/var/lib/grafana
      # Volumen de configuración
      - ./grafana/datasources:/etc/grafana/datasources
    #env_file:
    #  - ./grafana/config.monitoring
    networks:
      - backend
      - frontend
    restart: "always"

networks:
  frontend:
  backend:

volumes:
  prometheus-data: {}
  grafana_data: {}

