version: '3'

services:
  # Plataforma de recolección de métricas HTTP de los servicios monitoreados
  prometheus:
    image: prom/prometheus
    volumes:
      # Volumen de configuración
      - ./prometheus/:/etc/prometheus/
      # Volumen de datos
      - prometheus-data:/prometheus
    restart: "always"
    networks:
      - backend
    ports:
      - 9000:9000
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    links:
      - cadvisor:cadvisor
  # Analiza los recursos usados por los contendores
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - ./cadvisor/:/etc/cadvisor/
    ports:
      - 9001:9001
    networks:
      - backend
    restart: "always"
  # Visor de métricas y datos
  grafana:
    image: grafana/grafana
    depends_on: 
      - prometheus
    ports: 
      - 9003:9003
    volumes:
      # Volumen de datos
      - grafana_data:/var/lib/grafana
      # Volumen de configuración
      - ./grafana/datasources:/etc/grafana/datasources
    #env_file:
    #  - ./grafana/config.monitoring
    networks:
      - backend
      - frontend
    restart: "always"

networks:
  frontend:
  backend:

volumes:
  prometheus-data: {}
  grafana_data: {}

