version: '3'
services:
  python_backend:
    build: ./backend
    volumes:
      - python_backend:/var/backend
    expose:
      - 5501

  api_luces:
    depends_on:
      - python_backend
    build: ./apis/api_luces
    expose:
      - 5502

  api_puertas:
    depends_on:
      - python_backend
    build: ./apis/api_puertas
    expose:
      - 5503

  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
    expose:
      - 5504

  terminal:
    build: ./terminal
    expose:
      - 5505

volumes:
  python_backend:
  db_data:
