version: "3"

services:
  api1:
    image: gruizonestic/gestion_estacion_api1
    ports:
      - "5001:5000"

  api2:
    image: gruizonestic/gestion_estacion_api2
    ports:
      - "5002:5000"

  api3:
    image: gruizonestic/gestion_estacion_api3
    ports:
      - "5003:5000"

  api4:
    image: gruizonestic/gestion_estacion_api4
    ports:
      - "5004:5000"

  backend:
    image: gruizonestic/gestion_estacion_backend
    ports:
      - 5101-5102:5000

  frontend:
    image: gruizonestic/gestion_estacion_frontend
    depends_on:
      - backend
    ports:
      - 5103-5104:5000

  balanceador:
    image: gruizonestic/gestion_estacion_balanceador
    depends_on:
      - frontend
    ports:
      - 5105:5000

  api_trenes:
    image: gruizonestic/gestion_estacion_api_trenes
    ports:
      - "5106-5107:5000"

  puerta:
    image: gruizonestic/gestion_estacion_puerta
    ports:
      - "5201-5206:5000"
    depends_on:
      - puerta_backend

  puerta_backend:
    image: gruizonestic/gestion_estacion_puerta_backend
    ports:
      - "5207:5000"

  transferencias_diarias:
    image: gruizonestic/gestion_estacion_transferencias_diarias

  frontend_tpv:
    image: gruizonestic/gestion_estacion_frontend_tpv

  backend_ventas:
    image: gruizonestic/gestion_estacion_backend_ventas

  tpv:
    depends_on:
      - backend_ventas
    image: gruizonestic/gestion_estacion_tpv

  ftp:
    image: gruizonestic/gestion_estacion_ftp
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    volumes:
      - ~/ftp:/home/vsftpd

  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypass

  python_backend:
    image: gruizonestic/gestion_estacion_python_backend
    volumes:
      - python_backend:/var/backend

  api_luces:
    depends_on:
      - python_backend
    image: gruizonestic/gestion_estacion_api_luces

  api_puertas:
    depends_on:
      - python_backend
    image: gruizonestic/gestion_estacion_api_puertas

  db_servicio:
    image: mysql:8
    volumes:
      - db_data_servicio:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypass

  terminal:
    image: gruizonestic/gestion_estacion_terminal

volumes:
  db_data: {}
  python_backend: {}
  db_data_servicio: {}
  ftp: {}
