version: "3"

#Tenemos 6 puertas de acceso, acda una de ellas debe tener su propio sistema para poder permitir la entrada a los clientes, 
#al igual que las pantallas, tenemos que asegurar la mayor presencia por lo cual hemos obtado a tener los backends replicados en 3 contendeores
#para poder tener la mayor disponibilidad y no poder sufragar una cantidad de peticione smuy considerable.
services:
  puerta:
    build: ./frontend
    ports:
      - "5201-5206:5000"
    scale: 6
    depends_on:
      - puerta_backend1
      - puerta_backend2
      - puerta_backend3
  puerta_backend1:
    build: ./backend
    ports:
      - "5207:5000"
    hostname: puerta.backend1
  puerta_backend2:
    build: ./backend
    ports:
      - "5208:5000"
    hostname: puerta.backend2
  puerta_backend3:
    build: ./backend
    ports:
      - "5209:5000"
    hostname: puerta.backend3
