version: "3"

services:
  puerta:
    build: ./frontend
    ports:
      - "5201-5206:5000"
    scale: 6
    depends_on:
      - puerta_backend1
      - puerta_backend2
      - puerta_backend3
  puerta_backend1:
    build: ./backend
    ports:
      - "5207:5000"
    hostname: puerta.backend1
  puerta_backend2:
    build: ./backend
    ports:
      - "5208:5000"
    hostname: puerta.backend2
  puerta_backend3:
    build: ./backend
    ports:
      - "5209:5000"
    hostname: puerta.backend3
