version: "3"

services:
  ftp:
    build: .
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    volumes:
      - ~/ftp:/home/vsftpd
    hostname: prueba.ftp
volumes:
  ftp:
