version: "3"

services:
  backend1:
    build: ./backend
    hostname: "backend1-horarios"
    networks:
      - red_privada
  backend2:
    build: ./backend
    hostname: "backend2-horarios"
    networks:
      - red_privada
  frontend1:
    build: ./frontend
    hostname: "frontend1-horarios"
    networks:
      - red_privada
      - red_web  
  frontend2:
    build: ./frontend
    hostname: "frontend2-horarios"
    networks:
      - red_privada
      - red_web
  balanceador:
    build: ./balanceador
    ports:
      - "5105:80"
    hostname: "balanceador-horarios"
    networks:
      - red_publica
      - red_web

networks:
  red_privada: {}
  red_web: {}
  red_publica: {}