version: "3"

services:
  backend1:
    build: ./backend
    hostname: "backend1-horarios"
    ports:
      - 5101:5000
  backend2:
    build: ./backend
    hostname: "backend2-horarios"
    ports:
      - 5102:5000
  frontend1:
    build: ./frontend
    depends_on:
      - backend1
      - backend2
    hostname: "frontend1-horarios"
    ports:
      - 5103:5000
  frontend2:
    build: ./frontend
    depends_on:
      - backend1
      - backend2
    hostname: "frontend2-horarios"
    ports:
      - 5104:5000
  balanceador:
    build: ./balanceador
    depends_on:
      - frontend1
      - frontend2
    hostname: "balanceador-horarios"
    ports:
      - 5105:5000