version: "3"

#Hemos decididdo crear dos contenedores por cada servicio a esceción del balanceador ya que se trta de un servicio esencial, 
#en caso de que no se mutren los horarios a los pasajeros pueden perder su viaje haciendo una reclamación contra la empresa 
#por falta de información.
services:
  backend:
    build: ./backend
    hostname: "backend1-horarios"
    ports:
      - 5101-5102:5000
    scale: 2
  frontend:
    build: ./frontend
    depends_on:
      - backend
    hostname: "frontend1-horarios"
    ports:
      - 5103-5104:5000
    scale: 2
  balanceador:
    build: ./balanceador
    depends_on:
      - frontend
    hostname: "balanceador-horarios"
    ports:
      - 5105:5000
  api_trenes:
    build: ./api_trenes
    ports:
      - "5106:5000"