version: "3"

services:
  backend:
    build: ./backend
    hostname: "backend1-horarios"
    ports:
      - 5101-5102:5000
    scale: 2
  frontend:
    build: ./frontend
    depends_on:
      - backend
    hostname: "frontend1-horarios"
    ports:
      - 5103-5104:5000
    scale: 2
  balanceador:
    build: ./balanceador
    depends_on:
      - frontend
    hostname: "balanceador-horarios"
    ports:
      - 5105:5000